### ISSUE TITLE
请教大佬

### ISSUE THREAD

**Issue by Andy-Bai** [NENightElves/NewsSystem#1]
请问能否解释一下代码结构？文件夹下的文件分别实现什么功能？谢谢

**Comment by NENightElves** [comment]
# src
代码文件夹
- EncodingFilter.java 过滤器，将网站编码统一为UTF-8
- db.java 数据库连接类
- std.java 日期格式化
- newsManagement.java 新闻管理业务逻辑，增删改查等
- userModule.java 用户角色业务逻辑，增删改查等

# web
网站jsp文件夹
- checkauth*.jsp 权限检查
- nav*.jsp 导航条  
其余可从index.jsp与login.jsp入手，按照业务逻辑查看

> 此为老旧项目，仅使用jsp和少量servlet完成了所有功能，未使用框架，功能也过于简单，不建议学习

**Comment by Andy-Bai** [comment]
十分感谢
